version: 2
jobs: 
  build: 
    docker:
      - image: circleci/node:8.9.4
    environment:
    # from https://developer.salesforce.com/tools/sfdxcli
    - DX_CLI_URL: https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
    - PACKAGENAME: "0Ho0N000000CaT8SAK"
    - TESTLEVEL: RunLocalTests
    steps: 
      - checkout
      - run:
          name: Download CLI
          command: |
            # Create sfdx directory
            mkdir sfdx
            # Download Salesforce CLI
            wget -qO- $DX_CLI_URL | tar xJ -C sfdx --strip-components 1
      - run:
          name: Install CLI
          command: |
            # Create sfdx cli
            ./sfdx/install
            sfdx
      - run:
          name: Decrypt server key
          command: |
            #Decrypt server key
            openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out assets/server.key -base64 -K $DECRYPTION_KEY -iv $DECRYPTION_IV
      - run:
          name: Create scratch org
          command: |
            sfdx force --help
            #Authorize Dev Hub
            sfdx force:auth:jwt:grant --clientid $HUB_CONSUMER_KEY --jwtkeyfile assets/server.key --username $HUB_USER_NAME --setdefaultdevhubusername -a HubOrg
      - run:
          name: Run Apex Tests
          command: |
            #Run unit tests on scratch org
            sfdx force:apex:test:run --targetusername HubOrg --wait 10 --resultformat tap --codecoverage --testlevel $TESTLEVEL
